-- Seed data for Matiere table
-- Centre Régional des Oeuvres Universitaires de Ziguinchor (CROUS)
-- Université Assane Seck de Ziguinchor

-- INFORMATIQUE - Matériel et consommables informatiques
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('INFO-001', 'Ordinateur de bureau HP EliteDesk', 'DURABLE', 'INFORMATIQUE', 'PIECE', 450000, 5, true, NOW(), NOW()),
('INFO-002', 'Ordinateur portable Dell Latitude', 'DURABLE', 'INFORMATIQUE', 'PIECE', 550000, 3, true, NOW(), NOW()),
('INFO-003', 'Imprimante laser HP LaserJet Pro', 'DURABLE', 'INFORMATIQUE', 'PIECE', 180000, 2, true, NOW(), NOW()),
('INFO-004', 'Imprimante multifonction Canon', 'DURABLE', 'INFORMATIQUE', 'PIECE', 250000, 2, true, NOW(), NOW()),
('INFO-005', 'Scanner de documents Epson', 'DURABLE', 'INFORMATIQUE', 'PIECE', 120000, 1, true, NOW(), NOW()),
('INFO-006', 'Écran LCD 24 pouces Dell', 'DURABLE', 'INFORMATIQUE', 'PIECE', 85000, 5, true, NOW(), NOW()),
('INFO-007', 'Clavier sans fil Logitech', 'DURABLE', 'INFORMATIQUE', 'PIECE', 8500, 10, true, NOW(), NOW()),
('INFO-008', 'Souris optique sans fil', 'DURABLE', 'INFORMATIQUE', 'PIECE', 4500, 15, true, NOW(), NOW()),
('INFO-009', 'Disque dur externe 2TB', 'DURABLE', 'INFORMATIQUE', 'PIECE', 45000, 5, true, NOW(), NOW()),
('INFO-010', 'Clé USB 64GB', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 8000, 20, true, NOW(), NOW()),
('INFO-011', 'Câble HDMI 2 mètres', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 3500, 10, true, NOW(), NOW()),
('INFO-012', 'Multiprise parafoudre 6 prises', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 12000, 8, true, NOW(), NOW()),
('INFO-013', 'Cartouche d''encre HP noir', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 35000, 15, true, NOW(), NOW()),
('INFO-014', 'Cartouche d''encre HP couleur', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 42000, 15, true, NOW(), NOW()),
('INFO-015', 'Toner laser HP noir', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 55000, 10, true, NOW(), NOW()),
('INFO-016', 'Câble réseau RJ45 Cat6 - 5m', 'CONSOMMABLE', 'INFORMATIQUE', 'PIECE', 2500, 20, true, NOW(), NOW()),
('INFO-017', 'Switch réseau 24 ports', 'DURABLE', 'INFORMATIQUE', 'PIECE', 180000, 2, true, NOW(), NOW()),
('INFO-018', 'Routeur WiFi TP-Link', 'DURABLE', 'INFORMATIQUE', 'PIECE', 45000, 3, true, NOW(), NOW()),
('INFO-019', 'Onduleur 1000VA', 'DURABLE', 'INFORMATIQUE', 'PIECE', 95000, 5, true, NOW(), NOW()),
('INFO-020', 'Webcam HD Logitech', 'DURABLE', 'INFORMATIQUE', 'PIECE', 35000, 5, true, NOW(), NOW()),

-- MOBILIER - Meubles de bureau et équipements
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('MOB-001', 'Bureau métallique 1m60', 'DURABLE', 'MOBILIER', 'PIECE', 125000, 5, true, NOW(), NOW()),
('MOB-002', 'Bureau en bois massif 1m80', 'DURABLE', 'MOBILIER', 'PIECE', 180000, 3, true, NOW(), NOW()),
('MOB-003', 'Chaise de bureau ergonomique', 'DURABLE', 'MOBILIER', 'PIECE', 65000, 10, true, NOW(), NOW()),
('MOB-004', 'Fauteuil directeur en cuir', 'DURABLE', 'MOBILIER', 'PIECE', 150000, 3, true, NOW(), NOW()),
('MOB-005', 'Armoire métallique 2 portes', 'DURABLE', 'MOBILIER', 'PIECE', 95000, 5, true, NOW(), NOW()),
('MOB-006', 'Étagère bibliothèque 5 niveaux', 'DURABLE', 'MOBILIER', 'PIECE', 75000, 5, true, NOW(), NOW()),
('MOB-007', 'Table de réunion 8 places', 'DURABLE', 'MOBILIER', 'PIECE', 280000, 2, true, NOW(), NOW()),
('MOB-008', 'Chaise visiteur rembourrée', 'DURABLE', 'MOBILIER', 'PIECE', 35000, 15, true, NOW(), NOW()),
('MOB-009', 'Classeur à tiroirs 4 niveaux', 'DURABLE', 'MOBILIER', 'PIECE', 85000, 3, true, NOW(), NOW()),
('MOB-010', 'Porte-manteau sur pied', 'DURABLE', 'MOBILIER', 'PIECE', 25000, 5, true, NOW(), NOW()),
('MOB-011', 'Tableau blanc magnétique 120x90', 'DURABLE', 'MOBILIER', 'PIECE', 45000, 3, true, NOW(), NOW()),
('MOB-012', 'Corbeille à papier métallique', 'DURABLE', 'MOBILIER', 'PIECE', 8500, 20, true, NOW(), NOW()),
('MOB-013', 'Caisson mobile 3 tiroirs', 'DURABLE', 'MOBILIER', 'PIECE', 55000, 5, true, NOW(), NOW()),
('MOB-014', 'Présentoir à magazines', 'DURABLE', 'MOBILIER', 'PIECE', 35000, 3, true, NOW(), NOW()),
('MOB-015', 'Banc d''attente 3 places', 'DURABLE', 'MOBILIER', 'PIECE', 120000, 3, true, NOW(), NOW()),

-- FOURNITURE - Fournitures de bureau
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('FOUR-001', 'Ramette papier A4 80g (500 feuilles)', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 3500, 50, true, NOW(), NOW()),
('FOUR-002', 'Ramette papier A3 80g (500 feuilles)', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 6500, 20, true, NOW(), NOW()),
('FOUR-003', 'Stylo à bille bleu', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 2500, 30, true, NOW(), NOW()),
('FOUR-004', 'Stylo à bille rouge', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 2500, 20, true, NOW(), NOW()),
('FOUR-005', 'Stylo à bille noir', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 2500, 30, true, NOW(), NOW()),
('FOUR-006', 'Crayon à papier HB', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 1800, 20, true, NOW(), NOW()),
('FOUR-007', 'Gomme blanche', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 200, 50, true, NOW(), NOW()),
('FOUR-008', 'Taille-crayon métallique', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 300, 30, true, NOW(), NOW()),
('FOUR-009', 'Règle plastique 30cm', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 500, 30, true, NOW(), NOW()),
('FOUR-010', 'Agrafeuse de bureau', 'DURABLE', 'PAPETERIE', 'PIECE', 3500, 10, true, NOW(), NOW()),
('FOUR-011', 'Boîte d''agrafes 26/6 (5000 pcs)', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 1200, 30, true, NOW(), NOW()),
('FOUR-012', 'Perforatrice 2 trous', 'DURABLE', 'PAPETERIE', 'PIECE', 4500, 8, true, NOW(), NOW()),
('FOUR-013', 'Classeur à levier dos 8cm', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 2800, 40, true, NOW(), NOW()),
('FOUR-014', 'Chemise à rabat cartonnée', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 3500, 30, true, NOW(), NOW()),
('FOUR-015', 'Pochette plastique perforée A4', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 2500, 40, true, NOW(), NOW()),
('FOUR-016', 'Cahier 200 pages grand format', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 1500, 50, true, NOW(), NOW()),
('FOUR-017', 'Bloc-notes A4 100 feuilles', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 1200, 40, true, NOW(), NOW()),
('FOUR-018', 'Post-it jaune 76x76mm', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 1800, 30, true, NOW(), NOW()),
('FOUR-019', 'Marqueur permanent noir', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 800, 30, true, NOW(), NOW()),
('FOUR-020', 'Marqueur tableau blanc', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 1200, 20, true, NOW(), NOW()),
('FOUR-021', 'Surligneur jaune fluo', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 600, 30, true, NOW(), NOW()),
('FOUR-022', 'Correcteur liquide blanc', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 800, 25, true, NOW(), NOW()),
('FOUR-023', 'Ciseaux de bureau', 'DURABLE', 'PAPETERIE', 'PIECE', 1500, 15, true, NOW(), NOW()),
('FOUR-024', 'Cutter professionnel', 'DURABLE', 'PAPETERIE', 'PIECE', 2000, 10, true, NOW(), NOW()),
('FOUR-025', 'Colle liquide 250ml', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 1500, 20, true, NOW(), NOW()),
('FOUR-026', 'Ruban adhésif transparent', 'CONSOMMABLE', 'PAPETERIE', 'PIECE', 800, 30, true, NOW(), NOW()),
('FOUR-027', 'Trombones 50mm (boîte 100)', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 600, 25, true, NOW(), NOW()),
('FOUR-028', 'Pinces à dessin 32mm', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 1200, 20, true, NOW(), NOW()),
('FOUR-029', 'Élastiques assortis (boîte)', 'CONSOMMABLE', 'PAPETERIE', 'BOITE', 800, 15, true, NOW(), NOW()),
('FOUR-030', 'Enveloppes C4 kraft (paquet 50)', 'CONSOMMABLE', 'PAPETERIE', 'PAQUET', 3500, 20, true, NOW(), NOW()),

-- PRODUITS D'ENTRETIEN
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('ENT-001', 'Eau de javel 5L', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'LITRE', 2500, 30, true, NOW(), NOW()),
('ENT-002', 'Détergent liquide vaisselle 5L', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'LITRE', 4500, 25, true, NOW(), NOW()),
('ENT-003', 'Savon liquide mains 5L', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'LITRE', 5500, 20, true, NOW(), NOW()),
('ENT-004', 'Désinfectant sol 5L', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'LITRE', 6500, 20, true, NOW(), NOW()),
('ENT-005', 'Nettoyant vitres 750ml', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 2500, 15, true, NOW(), NOW()),
('ENT-006', 'Désodorisant spray 400ml', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 2000, 20, true, NOW(), NOW()),
('ENT-007', 'Sac poubelle 100L (rouleau 10)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PAQUET', 3500, 30, true, NOW(), NOW()),
('ENT-008', 'Sac poubelle 50L (rouleau 20)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PAQUET', 3000, 30, true, NOW(), NOW()),
('ENT-009', 'Balai en plastique', 'DURABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 3500, 10, true, NOW(), NOW()),
('ENT-010', 'Serpillière microfibre', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 2500, 15, true, NOW(), NOW()),
('ENT-011', 'Seau plastique 10L', 'DURABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 2000, 10, true, NOW(), NOW()),
('ENT-012', 'Pelle à poussière métallique', 'DURABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 2500, 8, true, NOW(), NOW()),
('ENT-013', 'Gants de ménage (paire)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 1500, 20, true, NOW(), NOW()),
('ENT-014', 'Éponge grattante (paquet 5)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PAQUET', 1200, 25, true, NOW(), NOW()),
('ENT-015', 'Chiffon microfibre (paquet 5)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PAQUET', 3500, 15, true, NOW(), NOW()),
('ENT-016', 'Papier toilette 2 plis (paquet 12)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PAQUET', 4500, 40, true, NOW(), NOW()),
('ENT-017', 'Essuie-mains papier (carton 20)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'CARTON', 18000, 15, true, NOW(), NOW()),
('ENT-018', 'Savon en pain (carton 72)', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'CARTON', 12000, 10, true, NOW(), NOW()),
('ENT-019', 'Insecticide spray 400ml', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 3500, 10, true, NOW(), NOW()),
('ENT-020', 'Désinfectant mains gel 500ml', 'CONSOMMABLE', 'PRODUIT_ENTRETIEN', 'PIECE', 4500, 20, true, NOW(), NOW()),

-- ÉQUIPEMENTS DIVERS
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('EQUIP-001', 'Climatiseur split 12000 BTU', 'DURABLE', 'EQUIPEMENT', 'PIECE', 350000, 2, true, NOW(), NOW()),
('EQUIP-002', 'Ventilateur sur pied', 'DURABLE', 'EQUIPEMENT', 'PIECE', 25000, 5, true, NOW(), NOW()),
('EQUIP-003', 'Réfrigérateur 200L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 280000, 2, true, NOW(), NOW()),
('EQUIP-004', 'Micro-ondes 25L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 65000, 3, true, NOW(), NOW()),
('EQUIP-005', 'Bouilloire électrique 2L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 15000, 5, true, NOW(), NOW()),
('EQUIP-006', 'Fontaine à eau', 'DURABLE', 'EQUIPEMENT', 'PIECE', 85000, 2, true, NOW(), NOW()),
('EQUIP-007', 'Téléphone fixe de bureau', 'DURABLE', 'EQUIPEMENT', 'PIECE', 25000, 5, true, NOW(), NOW()),
('EQUIP-008', 'Calculatrice de bureau', 'DURABLE', 'EQUIPEMENT', 'PIECE', 8500, 10, true, NOW(), NOW()),
('EQUIP-009', 'Lampe de bureau LED', 'DURABLE', 'EQUIPEMENT', 'PIECE', 12000, 8, true, NOW(), NOW()),
('EQUIP-010', 'Horloge murale', 'DURABLE', 'EQUIPEMENT', 'PIECE', 8000, 5, true, NOW(), NOW()),
('EQUIP-011', 'Extincteur 6kg poudre', 'DURABLE', 'EQUIPEMENT', 'PIECE', 35000, 10, true, NOW(), NOW()),
('EQUIP-012', 'Trousse de premiers secours', 'CONSOMMABLE', 'EQUIPEMENT', 'PIECE', 15000, 5, true, NOW(), NOW()),
('EQUIP-013', 'Projecteur multimédia', 'DURABLE', 'EQUIPEMENT', 'PIECE', 280000, 2, true, NOW(), NOW()),
('EQUIP-014', 'Écran de projection 200x200', 'DURABLE', 'EQUIPEMENT', 'PIECE', 95000, 2, true, NOW(), NOW()),
('EQUIP-015', 'Système audio portable', 'DURABLE', 'EQUIPEMENT', 'PIECE', 120000, 2, true, NOW(), NOW()),

-- MATÉRIEL MÉDICAL (pour infirmerie CROUS)
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('MED-001', 'Thermomètre digital', 'DURABLE', 'MATERIEL_MEDICAL', 'PIECE', 8500, 5, true, NOW(), NOW()),
('MED-002', 'Tensiomètre électronique', 'DURABLE', 'MATERIEL_MEDICAL', 'PIECE', 35000, 2, true, NOW(), NOW()),
('MED-003', 'Stéthoscope', 'DURABLE', 'MATERIEL_MEDICAL', 'PIECE', 25000, 2, true, NOW(), NOW()),
('MED-004', 'Compresses stériles (boîte 100)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 5500, 10, true, NOW(), NOW()),
('MED-005', 'Pansements adhésifs assortis', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 3500, 15, true, NOW(), NOW()),
('MED-006', 'Gants latex (boîte 100)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 8500, 20, true, NOW(), NOW()),
('MED-007', 'Alcool médical 70° (1L)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'LITRE', 4500, 10, true, NOW(), NOW()),
('MED-008', 'Coton hydrophile 500g', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'PAQUET', 3500, 10, true, NOW(), NOW()),
('MED-009', 'Bande élastique 10cm', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'PIECE', 2500, 15, true, NOW(), NOW()),
('MED-010', 'Sparadrap 5m', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'PIECE', 1500, 20, true, NOW(), NOW()),
('MED-011', 'Masques chirurgicaux (boîte 50)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 5500, 20, true, NOW(), NOW()),
('MED-012', 'Solution hydroalcoolique 500ml', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'PIECE', 4500, 15, true, NOW(), NOW()),
('MED-013', 'Paracétamol 500mg (boîte 100)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 3500, 10, true, NOW(), NOW()),
('MED-014', 'Sérum physiologique (boîte 40)', 'CONSOMMABLE', 'MATERIEL_MEDICAL', 'BOITE', 4500, 10, true, NOW(), NOW()),
('MED-015', 'Ciseaux médicaux', 'DURABLE', 'MATERIEL_MEDICAL', 'PIECE', 3500, 3, true, NOW(), NOW()),

-- VÉHICULES ET PIÈCES
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('VEH-001', 'Véhicule utilitaire 7 places', 'DURABLE', 'VEHICULE', 'PIECE', 12000000, 1, true, NOW(), NOW()),
('VEH-002', 'Motocyclette 125cc', 'DURABLE', 'VEHICULE', 'PIECE', 850000, 1, true, NOW(), NOW()),
('VEH-003', 'Huile moteur 5W30 (5L)', 'CONSOMMABLE', 'VEHICULE', 'LITRE', 25000, 10, true, NOW(), NOW()),
('VEH-004', 'Filtre à huile', 'CONSOMMABLE', 'VEHICULE', 'PIECE', 4500, 5, true, NOW(), NOW()),
('VEH-005', 'Filtre à air', 'CONSOMMABLE', 'VEHICULE', 'PIECE', 3500, 5, true, NOW(), NOW()),
('VEH-006', 'Batterie 12V 70Ah', 'CONSOMMABLE', 'VEHICULE', 'PIECE', 65000, 3, true, NOW(), NOW()),
('VEH-007', 'Pneu 195/65 R15', 'CONSOMMABLE', 'VEHICULE', 'PIECE', 45000, 8, true, NOW(), NOW()),
('VEH-008', 'Liquide de frein DOT4 (1L)', 'CONSOMMABLE', 'VEHICULE', 'LITRE', 8500, 5, true, NOW(), NOW()),
('VEH-009', 'Liquide de refroidissement (5L)', 'CONSOMMABLE', 'VEHICULE', 'LITRE', 12000, 5, true, NOW(), NOW()),
('VEH-010', 'Balai d''essuie-glace', 'CONSOMMABLE', 'VEHICULE', 'PIECE', 5500, 5, true, NOW(), NOW()),

-- AUTRES MATÉRIELS SPÉCIFIQUES
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('AUT-001', 'Groupe électrogène 10KVA', 'DURABLE', 'AUTRE', 'PIECE', 1500000, 1, true, NOW(), NOW()),
('AUT-002', 'Panneau solaire 250W', 'DURABLE', 'AUTRE', 'PIECE', 180000, 3, true, NOW(), NOW()),
('AUT-003', 'Batterie solaire 200Ah', 'DURABLE', 'AUTRE', 'PIECE', 250000, 2, true, NOW(), NOW()),
('AUT-004', 'Onduleur solaire 3000W', 'DURABLE', 'AUTRE', 'PIECE', 450000, 2, true, NOW(), NOW()),
('AUT-005', 'Caméra de surveillance IP', 'DURABLE', 'AUTRE', 'PIECE', 85000, 5, true, NOW(), NOW()),
('AUT-006', 'Enregistreur DVR 8 canaux', 'DURABLE', 'AUTRE', 'PIECE', 120000, 2, true, NOW(), NOW()),
('AUT-007', 'Câble électrique 2.5mm² (rouleau)', 'CONSOMMABLE', 'AUTRE', 'METRE', 800, 100, true, NOW(), NOW()),
('AUT-008', 'Interrupteur simple', 'CONSOMMABLE', 'AUTRE', 'PIECE', 1500, 20, true, NOW(), NOW()),
('AUT-009', 'Prise électrique murale', 'CONSOMMABLE', 'AUTRE', 'PIECE', 2000, 20, true, NOW(), NOW()),
('AUT-010', 'Ampoule LED 15W', 'CONSOMMABLE', 'AUTRE', 'PIECE', 3500, 30, true, NOW(), NOW()),
('AUT-011', 'Néon LED 18W 120cm', 'CONSOMMABLE', 'AUTRE', 'PIECE', 5500, 20, true, NOW(), NOW()),
('AUT-012', 'Rallonge électrique 10m', 'CONSOMMABLE', 'AUTRE', 'PIECE', 8500, 10, true, NOW(), NOW()),
('AUT-013', 'Cadenas de sécurité 50mm', 'DURABLE', 'AUTRE', 'PIECE', 4500, 10, true, NOW(), NOW()),
('AUT-014', 'Chaîne antivol 1.5m', 'DURABLE', 'AUTRE', 'PIECE', 12000, 5, true, NOW(), NOW()),
('AUT-015', 'Porte-documents en cuir', 'DURABLE', 'AUTRE', 'PIECE', 25000, 5, true, NOW(), NOW()),

-- MATÉRIEL DE CUISINE (pour restaurant universitaire)
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('CUIS-001', 'Gazinière 4 feux industrielle', 'DURABLE', 'EQUIPEMENT', 'PIECE', 450000, 2, true, NOW(), NOW()),
('CUIS-002', 'Réfrigérateur professionnel 600L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 850000, 1, true, NOW(), NOW()),
('CUIS-003', 'Congélateur coffre 400L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 550000, 1, true, NOW(), NOW()),
('CUIS-004', 'Marmite aluminium 50L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 45000, 5, true, NOW(), NOW()),
('CUIS-005', 'Marmite aluminium 100L', 'DURABLE', 'EQUIPEMENT', 'PIECE', 85000, 3, true, NOW(), NOW()),
('CUIS-006', 'Assiettes plates (lot 50)', 'CONSOMMABLE', 'EQUIPEMENT', 'LOT', 35000, 5, true, NOW(), NOW()),
('CUIS-007', 'Assiettes creuses (lot 50)', 'CONSOMMABLE', 'EQUIPEMENT', 'LOT', 35000, 5, true, NOW(), NOW()),
('CUIS-008', 'Verres à eau (lot 50)', 'CONSOMMABLE', 'EQUIPEMENT', 'LOT', 25000, 5, true, NOW(), NOW()),
('CUIS-009', 'Couverts inox (lot 100 pièces)', 'DURABLE', 'EQUIPEMENT', 'LOT', 55000, 3, true, NOW(), NOW()),
('CUIS-010', 'Plateau de service', 'DURABLE', 'EQUIPEMENT', 'PIECE', 4500, 30, true, NOW(), NOW()),

-- MATÉRIEL DE SPORT (pour activités étudiantes)
INSERT INTO "Matiere" (code, designation, type, categorie, unite, "valeurUnitaire", "seuilAlerte", actif, "createdAt", "updatedAt") VALUES
('SPORT-001', 'Ballon de football', 'CONSOMMABLE', 'EQUIPEMENT', 'PIECE', 15000, 10, true, NOW(), NOW()),
('SPORT-002', 'Ballon de basketball', 'CONSOMMABLE', 'EQUIPEMENT', 'PIECE', 18000, 5, true, NOW(), NOW()),
('SPORT-003', 'Ballon de volleyball', 'CONSOMMABLE', 'EQUIPEMENT', 'PIECE', 16000, 5, true, NOW(), NOW()),
('SPORT-004', 'Filet de volleyball', 'DURABLE', 'EQUIPEMENT', 'PIECE', 35000, 2, true, NOW(), NOW()),
('SPORT-005', 'Tapis de gymnastique', 'DURABLE', 'EQUIPEMENT', 'PIECE', 25000, 5, true, NOW(), NOW()),
('SPORT-006', 'Corde à sauter', 'CONSOMMABLE', 'EQUIPEMENT', 'PIECE', 2500, 15, true, NOW(), NOW()),
('SPORT-007', 'Sifflet d''arbitre', 'DURABLE', 'EQUIPEMENT', 'PIECE', 3500, 5, true, NOW(), NOW()),
('SPORT-008', 'Chronomètre digital', 'DURABLE', 'EQUIPEMENT', 'PIECE', 12000, 3, true, NOW(), NOW()),
('SPORT-009', 'Chasubles d''entraînement (lot 10)', 'CONSOMMABLE', 'EQUIPEMENT', 'LOT', 25000, 3, true, NOW(), NOW()),
('SPORT-010', 'Pompe à ballon', 'DURABLE', 'EQUIPEMENT', 'PIECE', 4500, 5, true, NOW(), NOW());
